// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rzhuympvvaoimidyxqxe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ6aHV5bXB2dmFvaW1pZHl4cXhlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc0NDA1MjQsImV4cCI6MjA1MzAxNjUyNH0.tnYs3ycfmTP7zMN0ttoxu6Xn7CSAKjslrtGLROqQpVE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);